target-version = "py312"
line-length = 79

[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[lint]
extend-select = [
    "B",    # flake8-bugbear
    "C4", # flake8-comprehensions
    "D",    # pydocstyle
    "E",    # pycodestyle
    "E501", # line too long (82 > 79 characters)
    "F",    # flake8
    "SIM",  # flake8-simplify
    "I",    # import order
    "UP",   # pyupgrade
]

[lint.pydocstyle]
convention = "google"
