[project]
name = "venv-purge"
version = "0.1.0"
description = "Purge python virtual environments"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "ruff>=0.9.10",
]
